//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amino Acid.
        /// </summary>
        public static string AminoAcid {
            get {
                return ResourceManager.GetString("AminoAcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Part Source.
        /// </summary>
        public static string AnimalPartSource {
            get {
                return ResourceManager.GetString("AnimalPartSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bacteria.
        /// </summary>
        public static string Bacteria {
            get {
                return ResourceManager.GetString("Bacteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAR.
        /// </summary>
        public static string BAR {
            get {
                return ResourceManager.GetString("BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begins With.
        /// </summary>
        public static string BeginsWith {
            get {
                return ResourceManager.GetString("BeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blend.
        /// </summary>
        public static string Blend {
            get {
                return ResourceManager.GetString("Blend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botanical.
        /// </summary>
        public static string Botanical {
            get {
                return ResourceManager.GetString("Botanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOTANICAL SUPPELMENT WITH VITAMIN MINERAL.
        /// </summary>
        public static string BOTANICALSUPPELMENTWITHVITAMINMINERAL {
            get {
                return ResourceManager.GetString("BOTANICALSUPPELMENTWITHVITAMINMINERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPSULE.
        /// </summary>
        public static string CAPSULE {
            get {
                return ResourceManager.GetString("CAPSULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical.
        /// </summary>
        public static string Chemical {
            get {
                return ResourceManager.GetString("Chemical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children 12M 4Y.
        /// </summary>
        public static string Children12M4Y {
            get {
                return ResourceManager.GetString("Children12M4Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your Language.
        /// </summary>
        public static string ChooseYourLanguage {
            get {
                return ResourceManager.GetString("ChooseYourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dietary Claim:.
        /// </summary>
        public static string DietaryClaim {
            get {
                return ResourceManager.GetString("DietaryClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIETARY SUPPLEMENT AMINOACID PROTEIN.
        /// </summary>
        public static string DIETARYSUPPLEMENTAMINOACIDPROTEIN {
            get {
                return ResourceManager.GetString("DIETARYSUPPLEMENTAMINOACIDPROTEIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIETARY SUPPLEMENT COMBINATION.
        /// </summary>
        public static string DIETARYSUPPLEMENTCOMBINATION {
            get {
                return ResourceManager.GetString("DIETARYSUPPLEMENTCOMBINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIETARY SUPPLEMENT COMBINATION OTHER.
        /// </summary>
        public static string DIETARYSUPPLEMENTCOMBINATIONOTHER {
            get {
                return ResourceManager.GetString("DIETARYSUPPLEMENTCOMBINATIONOTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIETARY SUPPLEMENT HERBAL BOTANICAL.
        /// </summary>
        public static string DIETARYSUPPLEMENTHERBALBOTANICAL {
            get {
                return ResourceManager.GetString("DIETARYSUPPLEMENTHERBALBOTANICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIETARY SUPPLEMENT MINERAL.
        /// </summary>
        public static string DIETARYSUPPLEMENTMINERAL {
            get {
                return ResourceManager.GetString("DIETARYSUPPLEMENTMINERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIETARY SUPPLEMENT NONNUTRIENT NONBOTANICAL.
        /// </summary>
        public static string DIETARYSUPPLEMENTNONNUTRIENTNONBOTANICAL {
            get {
                return ResourceManager.GetString("DIETARYSUPPLEMENTNONNUTRIENTNONBOTANICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIETARY SUPPLEMENT OTHER NUTRITIVE.
        /// </summary>
        public static string DIETARYSUPPLEMENTOTHERNUTRITIVE {
            get {
                return ResourceManager.GetString("DIETARYSUPPLEMENTOTHERNUTRITIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIETRAY SUPPLEMENT VITAMIN.
        /// </summary>
        public static string DIETRAYSUPPLEMENTVITAMIN {
            get {
                return ResourceManager.GetString("DIETRAYSUPPLEMENTVITAMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        public static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enzyme.
        /// </summary>
        public static string Enzyme {
            get {
                return ResourceManager.GetString("Enzyme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude.
        /// </summary>
        public static string Exclude {
            get {
                return ResourceManager.GetString("Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fat.
        /// </summary>
        public static string Fat {
            get {
                return ResourceManager.GetString("Fat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATTY ACCID FAT OIL.
        /// </summary>
        public static string FATTYACCIDFATOIL {
            get {
                return ResourceManager.GetString("FATTYACCIDFATOIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatty Acid.
        /// </summary>
        public static string FattyAcid {
            get {
                return ResourceManager.GetString("FattyAcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber.
        /// </summary>
        public static string Fiber {
            get {
                return ResourceManager.GetString("Fiber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form:.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45 Years And Above.
        /// </summary>
        public static string FortyFiveAndAbove {
            get {
                return ResourceManager.GetString("FortyFiveAndAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four years and above.
        /// </summary>
        public static string Fouryearsandabove {
            get {
                return ResourceManager.GetString("Fouryearsandabove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Years - 16 Years.
        /// </summary>
        public static string FourYearTo16 {
            get {
                return ResourceManager.GetString("FourYearTo16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUMMY.
        /// </summary>
        public static string GUMMY {
            get {
                return ResourceManager.GetString("GUMMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hormone.
        /// </summary>
        public static string Hormone {
            get {
                return ResourceManager.GetString("Hormone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infants children 12M.
        /// </summary>
        public static string Infantschildren12M {
            get {
                return ResourceManager.GetString("Infantschildren12M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient Categroy.
        /// </summary>
        public static string IngredientCategroy {
            get {
                return ResourceManager.GetString("IngredientCategroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient Filters.
        /// </summary>
        public static string IngredientFilters {
            get {
                return ResourceManager.GetString("IngredientFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient Name.
        /// </summary>
        public static string IngredientName {
            get {
                return ResourceManager.GetString("IngredientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string Ingredients {
            get {
                return ResourceManager.GetString("Ingredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIQUID.
        /// </summary>
        public static string LIQUID {
            get {
                return ResourceManager.GetString("LIQUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOZENGE.
        /// </summary>
        public static string LOZENGE {
            get {
                return ResourceManager.GetString("LOZENGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May Include.
        /// </summary>
        public static string MayInclude {
            get {
                return ResourceManager.GetString("MayInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mineral.
        /// </summary>
        public static string Mineral {
            get {
                return ResourceManager.GetString("Mineral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MULTI VITAMIN MULTI MINERAL.
        /// </summary>
        public static string MULTIVITAMINMULTIMINERAL {
            get {
                return ResourceManager.GetString("MULTIVITAMINMULTIMINERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Include.
        /// </summary>
        public static string MustInclude {
            get {
                return ResourceManager.GetString("MustInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Cateogory.
        /// </summary>
        public static string NoCateogory {
            get {
                return ResourceManager.GetString("NoCateogory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTHER.
        /// </summary>
        public static string OTHER1 {
            get {
                return ResourceManager.GetString("OTHER1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polysaccharide.
        /// </summary>
        public static string Polysaccharide {
            get {
                return ResourceManager.GetString("Polysaccharide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POWDER.
        /// </summary>
        public static string POWDER {
            get {
                return ResourceManager.GetString("POWDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregnant lactating women.
        /// </summary>
        public static string Pregnantlactatingwomen {
            get {
                return ResourceManager.GetString("Pregnantlactatingwomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer:.
        /// </summary>
        public static string Producer {
            get {
                return ResourceManager.GetString("Producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Filters.
        /// </summary>
        public static string ProductsFilters {
            get {
                return ResourceManager.GetString("ProductsFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein.
        /// </summary>
        public static string Protein {
            get {
                return ResourceManager.GetString("Protein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SINGLE VITAMIN SINGLE MINERAL.
        /// </summary>
        public static string SINGLEVITAMINSINGLEMINERAL {
            get {
                return ResourceManager.GetString("SINGLEVITAMINSINGLEMINERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 Years - 45 Years.
        /// </summary>
        public static string SixteenTo45 {
            get {
                return ResourceManager.GetString("SixteenTo45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTGL CAPSULE.
        /// </summary>
        public static string SOFTGLCAPSULE {
            get {
                return ResourceManager.GetString("SOFTGLCAPSULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplement Form.
        /// </summary>
        public static string SupplementForm {
            get {
                return ResourceManager.GetString("SupplementForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplements.
        /// </summary>
        public static string Supplements {
            get {
                return ResourceManager.GetString("Supplements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TABLET.
        /// </summary>
        public static string TABLET {
            get {
                return ResourceManager.GetString("TABLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Group:.
        /// </summary>
        public static string TargetGroup {
            get {
                return ResourceManager.GetString("TargetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN.
        /// </summary>
        public static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varbohydrate.
        /// </summary>
        public static string Varbohydrate {
            get {
                return ResourceManager.GetString("Varbohydrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin.
        /// </summary>
        public static string Vitamin {
            get {
                return ResourceManager.GetString("Vitamin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website:.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
